### ISSUE TITLE
Better method to handle Overflowed answers.

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/Calculator#38]
### Is your feature request related to a problem? Please describe.

<img src="https://user-images.githubusercontent.com/106915790/219704392-812b2cd5-7525-4053-ad1c-56e2ff994113.png" width="40%" />

As we can see from the above screenshot, the answers which are overflowed are being showed as an **Alert Dialog box** which doesn't looks much good. So, it should be handled in a more or good manner.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhruv-porwal** [comment]
Better method to handle Overflowed answers::

Overflowed answers can occur in a variety of contexts, such as when a computation exceeds the limits of the data type being used, or when the output of a model or algorithm is too large to be easily processed. Here are some methods to handle overflowed answers:



Use a modulo operation: In some cases, the overflow may occur due to the result being too large to be represented by the available memory. Using a modulo operation to keep the result within a smaller range can help avoid overflow errors.

Use scientific notation: If the values being computed are very large or small, representing them in scientific notation can help avoid overflow errors.

Handle the overflow as an exception: When the overflow occurs, catch the exception and handle it appropriately. For example, you may want to return an error message, or terminate the program gracefully.

We can write a toast message/pop up telling very large values.

**Comment by TheNPDev** [comment]
Hey @AyushAgnihotri2025 , I also want to work on this issue.
Please it to me under IWOC label

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @TheNPDev .....

**Comment by AyushAgnihotri2025** [comment]
Completed #46
